INSERT IGNORE INTO authorities VALUE (1, 'ROLE_ADMIN'); 
INSERT IGNORE INTO authorities VALUE (2, 'ROLE_EDITOR'); 
INSERT IGNORE INTO authorities VALUE (3, 'ROLE_READER');

INSERT IGNORE INTO LANGUAGE VALUES ('IT', 'ITALIAN', true);
INSERT IGNORE INTO LANGUAGE VALUES ('FR', 'FRENCH', true);
INSERT IGNORE INTO LANGUAGE VALUES ('ES', 'SPANISH', true);
INSERT IGNORE INTO LANGUAGE VALUES ('DE', 'GERMAN', true);
INSERT IGNORE INTO LANGUAGE VALUES ('NL', 'DUTCH', true);
INSERT IGNORE INTO LANGUAGE VALUES ('NO', 'NORVEGIAN', false);



